#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isBalanced' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isBalanced(s):
    # Write your code here
    stack = []
    answer = "YES"
    opens = ['{', '[', '(']
    closes = ['}', ']', ')']

    for i in range(len(s)):
        if s[i] in opens:
            stack.append(s[i])
        elif s[i] in closes:
            idx = closes.index(s[i])
            if len(stack) > 0 and stack[-1] == opens[idx]:
                stack.pop()
            else:
                answer = "NO"
                break
    if len(stack) != 0:
        answer = "NO"
    return answer

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
