#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'caesarCipher' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

def caesarCipher(s, k):
    # Write your code here
    k %= 26
    result = ""
    for cha in s:
        if cha.isupper():
            ci = ord(cha) + k
            if ci <= ord('Z'):
                result += chr(ci)
            else:
                result += chr(ci - 26)
        elif cha.islower():
            ci = ord(cha) + k
            if ci <= ord('z'):
                result += chr(ci)
            else:
                result += chr(ci - 26)
        else:
                result += cha
    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = input()

    k = int(input().strip())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
