#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lonelyinteger' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def lonelyinteger(a):
    # Write your code here
    a.sort()
    before = a[0]
    num =1
    
    for i in range(len(a)):
        if i==0:
            if len(a)==1:
                return a[i]
            continue
        if before != a[i]:
            if num == 1:
                return a[i-1]
            if len(a)==i+1:
                return a[i]
            num = 1
        else: 
            num=num+1
        before = a[i]
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = lonelyinteger(a)

    fptr.write(str(result) + '\n')

    fptr.close()
