#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    pos = 0
    zero = 0
    neg = 0
    length = len(arr)
    
    for i in arr:
        if i > 0:
            pos+=1
        elif i==0:
            zero+=1
        else:
            neg+=1

    print(format(pos/length,".6f"))
    print(format(neg/length,".6f"))
    print(format(zero/length,".6f"))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
