#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    hour = int(s[:2])
    ans = ""
    if 'PM'==s[8:]:
        if hour==12:
            ans = s[:8]
        else:
            hour = hour+12
            ans = str(hour)+s[2:8]
            
    else:
        if hour == 12:
            ans = "00"+s[2:8]
        else:
            ans = s[:8]
            
    return ans
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
